import test from 'node:test';
import assert from 'node:assert/strict';
import { deflateSync } from 'node:zlib';
import { readFile } from 'node:fs/promises';
import worker from '../workers/pumplite-rpc/worker.js';
import { uploadMetadataPart } from '../web/metadata-upload.js';
const origin='https://frymastercheese.github.io', host='https://pumplite-rpc.coreyedge123.workers.dev';
const cid='bafkrei'+'a'.repeat(52);
const token='Bearer synthetic-upload-grant-0001';
function chunk(type,data){const b=Buffer.alloc(data.length+12);b.writeUInt32BE(data.length);b.write(type,4);data.copy(b,8);let c=0xffffffff;for(const v of b.subarray(4,-4)){c^=v;for(let i=0;i<8;i++)c=(c>>>1)^((c&1)?0xedb88320:0);}b.writeUInt32BE((c^0xffffffff)>>>0,b.length-4);return b;}
function png(){const h=Buffer.alloc(13);h.writeUInt32BE(1);h.writeUInt32BE(1,4);h[8]=8;h[9]=6;return Buffer.concat([Buffer.from([137,80,78,71,13,10,26,10]),chunk('IHDR',h),chunk('IDAT',deflateSync(Buffer.from([0,255,0,0,255]))),chunk('IEND',Buffer.alloc(0))]);}
const document={name:'Token',symbol:'TOK',description:'Untrusted text <script>',imageCid:cid};
function env(){return {METADATA_UPLOADS_ENABLED:'true',PINATA_JWT:'synthetic-not-a-jwt',UPLOAD_GUARD:{fetch:async()=>new Response(null,{status:204})}};}
function req(path='/metadata/image',body=png(),headers={},method='POST'){return new Request(host+path,{method,headers:{Origin:origin,'Content-Type':path.endsWith('image')?'image/png':'application/json',Authorization:token,...headers},...(method==='POST'?{body}:{})});}
async function run(request,e=env()){return worker.fetch(request,e);}
function upstream(t,mode='ok'){let calls=0;t.mock.method(globalThis,'fetch',async(url,o)=>{calls++;assert.equal(url,'https://uploads.pinata.cloud/v3/files');assert.equal(o.redirect,'manual');assert.equal(o.headers.Authorization,'Bearer synthetic-not-a-jwt');assert.equal(o.body.get('network'),'public');const file=o.body.get('file');assert.ok(['token-logo.png','token-metadata.json'].includes(file.name));if(file.type==='application/json')assert.deepEqual(JSON.parse(await file.text()),{name:document.name,symbol:document.symbol,description:document.description,image:'ipfs://'+cid});return mode==='ok'?Response.json({data:{cid,user_id:'do-not-forward',private:'do-not-forward'}}):new Response('sensitive-upstream-body',{status:403});});return ()=>calls;}
for(const [name,request,e,status] of [
 ['missing secret',()=>req(),()=>({...env(),PINATA_JWT:undefined}),503],
 ['disabled',()=>req(),()=>({...env(),METADATA_UPLOADS_ENABLED:'false'}),503],
 ['missing guard',()=>req(),()=>({...env(),UPLOAD_GUARD:undefined}),503],
 ['wrong origin',()=>req(undefined,undefined,{Origin:'https://evil.example'}),env,403],
 ['null origin',()=>req(undefined,undefined,{Origin:'null'}),env,403],
 ['wrong method',()=>req(undefined,undefined,{},'GET'),env,404],
 ['no authorization',()=>req(undefined,undefined,{Authorization:''}),env,401],
 ['SVG',()=>req(undefined,'<svg/>',{'Content-Type':'image/svg+xml'}),env,415],
 ['malformed multipart',()=>req(undefined,'broken',{'Content-Type':'multipart/form-data; boundary=broken'}),env,415],
 ['invalid PNG',()=>req(undefined,'not png'),env,400],
 ['oversized body',()=>req(undefined,new Uint8Array(524289)),env,413],
 ['oversized declared body',()=>req(undefined,undefined,{'Content-Length':'524289'}),env,413],
 ['malformed JSON',()=>req('/metadata/json','{'),env,400],
 ['JSON array',()=>req('/metadata/json','[]'),env,400],
 ['unknown field',()=>req('/metadata/json',JSON.stringify({...document,url:'https://internal.example'})),env,400],
 ['long name',()=>req('/metadata/json',JSON.stringify({...document,name:'x'.repeat(33)})),env,400],
 ['UTF8 name',()=>req('/metadata/json',JSON.stringify({...document,name:'😀'.repeat(9)})),env,400],
 ['long description',()=>req('/metadata/json',JSON.stringify({...document,description:'x'.repeat(2001)})),env,400],
 ['invalid image URI',()=>req('/metadata/json',JSON.stringify({...document,imageCid:'https://internal.example'})),env,400],
 ['denied grant',()=>req(),()=>({...env(),UPLOAD_GUARD:{fetch:async()=>new Response(null,{status:403})}}),403]
])test('metadata rejects '+name,async t=>{t.mock.method(globalThis,'fetch',()=>assert.fail('No upstream call permitted'));const r=await run(request(),e());assert.equal(r.status,status);assert.ok(!(await r.text()).includes('synthetic-not-a-jwt'));});
for(const path of ['/metadata/image','/metadata/json','/rpc'])test('exact-origin preflight '+path,async()=>{const r=await run(req(path,null,{},'OPTIONS'));assert.equal(r.status,204);assert.equal(r.headers.get('Access-Control-Allow-Origin'),origin);assert.equal(r.headers.get('Access-Control-Allow-Headers'),path==='/rpc'?'Content-Type, solana-client':'Content-Type, Authorization');});
for(const kind of ['image','json'])test('mocked '+kind+' upload returns CID only and records receipt',async t=>{const calls=upstream(t), e=env(),guard=[];e.UPLOAD_GUARD.fetch=async(url,o)=>{guard.push([url,JSON.parse(o.body)]);return new Response(null,{status:204});};const r=await run(req('/metadata/'+kind,kind==='image'?png():JSON.stringify(document)),e);assert.equal(r.status,200);assert.deepEqual(await r.json(),{cid,uri:'ipfs://'+cid});assert.equal(calls(),1);assert.equal(guard.length,2);assert.match(guard[0][1].sha256,/^[a-f0-9]{64}$/);assert.equal(guard[1][1].cid,cid);if(kind==='json')assert.equal(guard[0][1].imageCid,cid);});
test('sanitized upstream failure, no retry',async t=>{const calls=upstream(t,'fail');const r=await run(req());assert.equal(r.status,502);assert.deepEqual(await r.json(),{error:'Metadata provider rejected upload',stage:'pinata_http',providerStatus:403});assert.equal(calls(),1);});
test('upstream malformed/oversized/error responses and receipt failures are sanitized',async t=>{for(const mode of ['bad-json','oversize','bad-cid','throw','receipt']){t.mock.method(globalThis,'fetch',async()=>{if(mode==='throw')throw Error('synthetic confidential exception');if(mode==='bad-json')return new Response('private-invalid-json');if(mode==='oversize')return new Response('x'.repeat(8193));return Response.json({data:{cid:mode==='bad-cid'?'invalid':cid}});});const e=env();if(mode==='receipt')e.UPLOAD_GUARD.fetch=async url=>new Response(null,{status:url.endsWith('complete')?503:204});const r=await run(req(),e);assert.equal(r.status,502);assert.ok(!(await r.text()).includes('private'));}});
test('PNG rejects trailing payload, CRC corruption, metadata chunks and invalid compressed pixels',async t=>{t.mock.method(globalThis,'fetch',()=>assert.fail('No upload'));const good=png(),broken=Buffer.from(good);broken[broken.length-1]^=1;const header=good.subarray(0,33);for(const bytes of [Buffer.concat([good,Buffer.from('payload')]),broken,Buffer.concat([header,chunk('tEXt',Buffer.from('x')),good.subarray(33)]),Buffer.concat([header,chunk('IDAT',Buffer.from('bad')),chunk('IEND',Buffer.alloc(0))])])assert.equal((await run(req(undefined,bytes))).status,400);});
test('timeout aborts a stalled authorization without uploading',async t=>{t.mock.timers.enable({apis:['setTimeout']});let entered;const waiting=new Promise(r=>entered=r);const e=env();e.UPLOAD_GUARD.fetch=()=>{entered();return new Promise(()=>{});};t.mock.method(globalThis,'fetch',()=>assert.fail('No upload'));const response=run(req(),e);await waiting;t.mock.timers.tick(15001);assert.equal((await response).status,502);});
test('health and RPC success stay intact; reviewed writes validate input and unapproved writes stay blocked',async t=>{assert.equal(await(await run(new Request(host+'/health'))).text(),'ok');const genesis='5eykt4UsFv8P8NJdTREpY1vzqKqZKvdpKuc147dw2N9d';const raw=JSON.stringify({jsonrpc:'2.0',id:1,result:genesis});t.mock.method(globalThis,'fetch',async()=>new Response(raw));const e={HELIUS_RPC_URL:'https://rpc.invalid/fixture'};const r=await run(req('/rpc',JSON.stringify({jsonrpc:'2.0',id:1,method:'getGenesisHash'})),e);assert.equal(await r.text(),raw);const malformedSend=await run(req('/rpc',JSON.stringify({jsonrpc:'2.0',id:1,method:'sendTransaction'})),e);assert.equal(malformedSend.status,400);const blocked=await run(req('/rpc',JSON.stringify({jsonrpc:'2.0',id:1,method:'requestAirdrop'})),e);assert.equal(blocked.status,403);assert.equal((await run(req('/rpc','[]'),e)).status,400);});
test('RPC upstream errors never reveal upstream bodies',async t=>{t.mock.method(globalThis,'fetch',async()=>new Response('sensitive',{status:403}));const r=await run(req('/rpc',JSON.stringify({jsonrpc:'2.0',id:1,method:'getGenesisHash'})),{HELIUS_RPC_URL:'https://rpc.invalid/fixture'});assert.equal(r.status,502);assert.deepEqual(await r.json(),{error:'RPC service temporarily unavailable'});});
test('frontend preparation fails closed; scoped client returns only canonical IPFS identity',async t=>{let calls=0;t.mock.method(globalThis,'fetch',async(url,o)=>{calls++;assert.equal(url,host+'/metadata/json');assert.equal(o.credentials,'omit');return Response.json({cid,uri:'ipfs://'+cid});});await assert.rejects(uploadMetadataPart({},'json',document,token),/not enabled/);assert.equal(calls,0);assert.deepEqual(await uploadMetadataPart({enabled:true},'json',document,token),{cid,uri:'ipfs://'+cid});assert.equal(calls,1);const config=JSON.parse(await readFile('config.json'));assert.equal(config.solana.transactionsEnabled,true);assert.equal(config.base.transactionsEnabled,true);assert.equal(config.solana.protocol,'tiny');assert.equal(config.solana.programId,'3CHqrdJzwWQj1QikCzpjBhC8iQ3paaMtD1x9kwoW1rku');assert.equal(config.solana.ammProgramId,undefined);assert.equal(config.solana.mayhemProgramId,undefined);assert.equal(config.base.factory,'0xdA8c34819ae397FD4bE3C95947DEA64f4A3278f4');assert.equal(config.metadataUploads?.enabled,true);});

test('missing Origin is rejected before any metadata or RPC processing',async t=>{t.mock.method(globalThis,'fetch',()=>assert.fail('No upstream'));const r=req();r.headers.delete('Origin');assert.equal((await run(r)).status,403);});
test('stalled Pinata response is bounded and never retried',async t=>{t.mock.timers.enable({apis:['setTimeout']});let entered;const started=new Promise(r=>entered=r);let calls=0;t.mock.method(globalThis,'fetch',()=>{calls++;entered();return new Promise(()=>{});});const response=run(req());await started;t.mock.timers.tick(15001);const r=await response;assert.equal(r.status,502);assert.equal(calls,1);assert.deepEqual(await r.json(),{error:'Metadata provider request failed',stage:'pinata_fetch'});});
test('RPC request validation and missing upstream configuration remain intact',async t=>{t.mock.method(globalThis,'fetch',()=>assert.fail('No upstream'));for(const [request,status] of [[req('/rpc','{}',{'Content-Type':'text/plain'}),415],[req('/rpc','{'),400],[req('/rpc',JSON.stringify({method:'getGenesisHash'})),400],[req('/rpc','x'.repeat(100001)),413],[req('/rpc',JSON.stringify({jsonrpc:'2.0',method:'getGenesisHash'})),503]])assert.equal((await run(request,{})).status,status);});
test('bundled Worker preserves RPC and metadata disabled by default',async t=>{const {build}=await import('esbuild');const result=await build({entryPoints:['workers/pumplite-rpc/worker.js'],bundle:true,write:false,format:'esm',platform:'browser',target:'es2022'});const bundled=(await import('data:text/javascript;base64,'+Buffer.from(result.outputFiles[0].contents).toString('base64'))).default;t.mock.method(globalThis,'fetch',()=>assert.fail('No upstream'));assert.equal(await(await bundled.fetch(new Request(host+'/health'),{})).text(),'ok');assert.equal((await bundled.fetch(req(),{})).status,503);});
